### ISSUE TITLE
Beta Feedback (Milestone 9)

### ISSUE THREAD

**Issue by reactivepixel** [fs-tech-degs/capstone-DVBrown93#112]
**General Notes**
* There are variations on button colors through the application.
* `/explore` "Get your stories featured here" is a dead link. This should go to a section that explains how to get featured.
* Uploading a new avatar image did not work immediately. It did load in after several refreshes and other page loads. I'm not setting this as an action item as I can't replicate the problem right now but will look for this in the final public release.
* Looks like the styling for the analytics is starting to come in.

**Action Items**
* [ ] Review ALL pages for white on white text.
* [ ] Standardize interaction color choices. (link and button colors)
* [ ] Various pages have styling errors.
* [ ] Ability to write inside of a paragraph on the `/create2` route seems to not work. 
* [ ] All routes should be semantically named, `create2`is a good example of a bad practice.
* [ ] Paragraphs/Blocks of text should not be centered. Here's some [further reading](https://guppyfishweb.com/web-design/text-alignment-center/) on why.

**Follow up**
This list is for your own breakdown of some feedback points we will be looking at in the public release. For a follow-up, just ensure that these items, as well as any outstanding enhancements,  have been completed for the public release.

> Close this issue after **all** action items and follow up has been completed.

**Team Members Involved**

| Team Member        |
| ------------- |
| Chapman |
